
[Energy]
	#Multiplier for all power generation in the mod
	#Range: 0.001 ~ 1000.0
	generation_multiplier = 1.0
	#Allow solar panel registration: du, elite, advanced, basic
	register_panel = [false, false, false, false]
	#Solar panel power generation: du, elite, advanced, basic
	panel_power = [400, 1500, 100, 25]
	#Allow rtg registration: uranium_rtg, americium_rtg, plutonium_rtg, californium_rtg
	register_rtg = [true, true, true, true]
	#rtg generation: uranium_rtg, americium_rtg, plutonium_rtg, californium_rtg
	rtg_power = [128, 512, 2048, 8192]
	#rtg radiation: uranium_rtg, americium_rtg, plutonium_rtg, californium_rtg
	rtg_radiation = [560, 57800, 200000, 1900000]
	#Steam turbine (one block) base power gen
	steam_turbine_power_gen = 50
	#Decay Generator base power gen
	decay_generator_power_gen = 100

[energy_storage]
	ligtning_rod_charge = 1000000
	#Allow block registration: basic_voltaic_pile, elite_voltaic_pile, advanced_voltaic_pile, basic_lithium_ion_battery, elite_lithium_ion_battery, du_lithium_ion_battery, du_voltaic_pile, advanced_lithium_ion_battery
	energy_block_registration = [false, false, false, false, false, false, false, false]
	#Storage: basic_voltaic_pile, elite_voltaic_pile, advanced_voltaic_pile, basic_lithium_ion_battery, elite_lithium_ion_battery, du_lithium_ion_battery, du_voltaic_pile, advanced_lithium_ion_battery
	energy_block_storage = [1600000, 102400000, 6400000, 32000000, 2048000000, 512000000, 25600000, 128000000]
	lithium_ion_battery_storage = 1000000
	qnp_energy_storage = 2000000
	qnp_energy_per_block = 200

[Misc]
	#Debug logging. Enable in case of issues to collect more data
	debug_logging = false
	#Enable periodical re-validation of multiblocks.
	#Multiblocks are tracking block changes and re-validate structure if needed.
	#But it is possible when some events won't be tracked properly.
	#This is why each multiblock periodically re-check it's structure.
	#Disable if you have performance issues with multiblocks.
	scheduled_validation = true

[storage_blocks]
	#Blocks to store items, fluids, etc...
	#Allow container registration: advanced_barrel, basic_barrel, elite_barrel, du_barrel
	container_block_registration = [false, false, false, false]
	#Allow barrel registration: advanced_barrel, basic_barrel, elite_barrel, du_barrel
	barrel_block_registration = [false, false, false, false]
	#Barrel capacity in Buckets: advanced_barrel, basic_barrel, elite_barrel, du_barrel
	barrel_capacity = [512, 128, 8192, 2048]

