
#Settings for Fusion Reactor
[general]
	#EXPL FE requirement.
	#Range: 2048000000 ~ 20480000000
	expl_fe = 10240000000
	#Laser burst distance.
	#Range: 8 ~ 64
	min_size = 32
	#Multiplier for kugelblitz chamber FE generation.
	#Range: 0.001 ~ 1000.0
	fe_generation_multiplier = 1.0
	#Adjust rate of blackhole evaporation.
	#Range: 0.001 ~ 1000.0
	blackhole_evaporation_rate = 1.0

