
[lithium]
	#Ore generation settings for lithium
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60

[platinum]
	#Ore generation settings for platinum
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 0

[thorium]
	#Ore generation settings for thorium
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60

[tin]
	#Ore generation settings for tin
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = 4
	#Range: -64 ~ 255
	max_height = 60

[magnesium]
	#Ore generation settings for magnesium
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60

[silver]
	#Ore generation settings for silver
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60

[cobalt]
	#Ore generation settings for cobalt
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60

[uranium]
	#Ore generation settings for uranium
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60

[zinc]
	#Ore generation settings for zinc
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = 4
	#Range: -64 ~ 255
	max_height = 60

[boron]
	#Ore generation settings for boron
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60

[lead]
	#Ore generation settings for lead
	register = false
	dimensions = [0, -4848]
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = 4
	#Range: -64 ~ 255
	max_height = 60

